name: OnePlanAndroid — CI
on:
  push:
    branches: [ main, refactor/v1 ]
  pull_request:
    branches: [ main, refactor/v1 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Pre-build Source Dump (always)
        if: always()
        run: |
          OUT_TXT="FULL_CODE_DUMP.txt"
          echo "# OnePlan — full source dump ($(date -u +%Y-%m-%dT%H:%M:%SZ))" > "$OUT_TXT"
          git ls-files | sort >> "$OUT_TXT"
          echo >> "$OUT_TXT"
          git ls-files | while read -r f; do
            echo -e "\n\n----- FILE: $f -----\n" >> "$OUT_TXT"
            sed -n '1,400p' "$f" >> "$OUT_TXT" || true
          done
          sudo apt-get update -y && sudo apt-get install -y pandoc zip
          pandoc "$OUT_TXT" -o FULL_CODE_DUMP.docx --standalone || true
          zip -r FULL_CODE_DUMP.zip "$OUT_TXT" app *.kts *.gradle **/*.kt **/*.xml || true

      - name: Build debug APK
        run: ./gradlew --no-daemon --stacktrace :app:assembleDebug

      - name: Upload APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: oneplan-debug-apks
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error

      - name: Upload FULL_CODE_DUMP artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: FULL_CODE_DUMPS
          path: |
            FULL_CODE_DUMP.txt
            FULL_CODE_DUMP.docx
            FULL_CODE_DUMP.zip
