name: OnePlanAndroid — CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Use hosted Gradle so we don't depend on ./gradlew or wrapper JAR
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.7'
          cache-read-only: false

      # Ensure AndroidX flags exist even if the file isn't in the repo
      - name: Ensure gradle.properties
        run: |
          touch gradle.properties
          grep -q '^android.useAndroidX=' gradle.properties || echo 'android.useAndroidX=true' >> gradle.properties
          grep -q '^android.enableJetifier=' gradle.properties || echo 'android.enableJetifier=true' >> gradle.properties
          grep -q '^org.gradle.jvmargs=' gradle.properties || echo 'org.gradle.jvmargs=-Xmx2048m -Dkotlin.daemon.jvm.options=-Xmx1024m' >> gradle.properties

      - name: Build debug APK
        run: gradle --no-daemon --stacktrace assembleDebug

      - name: Upload Debug APKs
        uses: actions/upload-artifact@v4
        with:
          name: oneplan-debug-apks
          path: '**/build/outputs/apk/debug/*.apk'


