name: OnePlanAndroid — CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Use the maintained Gradle action (handles caching, toolchains)
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      # Ensure AndroidX flags exist (idempotent)
      - name: Ensure gradle.properties for AndroidX
        run: |
          set -euo pipefail
          if [ ! -f gradle.properties ]; then
            printf "android.useAndroidX=true\nandroid.enableJetifier=true\n" > gradle.properties
          else
            grep -q '^android.useAndroidX=true' gradle.properties || echo 'android.useAndroidX=true' >> gradle.properties
            grep -q '^android.enableJetifier=true' gradle.properties || echo 'android.enableJetifier=true' >> gradle.properties
          fi

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew --no-daemon --stacktrace assembleDebug

      - name: Upload Debug APKs
        uses: actions/upload-artifact@v4
        with:
          name: oneplan-debug-apks
          path: '**/build/outputs/apk/debug/*.apk'

