name: OnePlanAndroid — CI
on:
  push:
    branches: [ main, refactor/** ]
  pull_request:
    branches: [ main, refactor/** ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v3

      - name: Build (debug)
        run: ./gradlew --no-daemon --stacktrace :app:assembleDebug

      - name: Full code dump (always)
        if: always()
        run: |
          echo "# FULL CODE DUMP — $(date -u)" > FULL_CODE_DUMP.txt
          echo >> FULL_CODE_DUMP.txt
          echo "## File list" >> FULL_CODE_DUMP.txt
          git ls-files | sort >> FULL_CODE_DUMP.txt
          echo >> FULL_CODE_DUMP.txt
          echo "## Sources" >> FULL_CODE_DUMP.txt
          git ls-files ':!**/*.png' ':!**/*.jpg' ':!**/*.jpeg' ':!**/*.webp' ':!**/*.gif' ':!**/*.keystore' ':!**/*.jks' \
          | while read -r f; do
              echo -e "\n\n-----8<----- FILE: $f -----8<-----\n" >> FULL_CODE_DUMP.txt
              sed -n '1,5000p' "$f" >> FULL_CODE_DUMP.txt || true
            done

      - name: Upload APK(s)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: oneplan-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: warn

      - name: Upload FULL_CODE_DUMP
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: FULL_CODE_DUMP
          path: FULL_CODE_DUMP.txt
