name: OnePlanAndroid — CI
on:
  push:
    branches: [ main, refactor/**, feature/** ]
  pull_request:
    branches: [ main, refactor/**, feature/** ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Debug APK
        run: gradle --no-daemon --stacktrace :app:assembleDebug

      - name: Upload APK(s)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: oneplan-alpha-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: warn

      - name: Generate FULL_CODE_DUMP (always)
        if: always()
        run: |
          OUT="FULL_CODE_DUMP.txt"
          echo "# OnePlanAlpha — full source dump ($(date -u +%Y-%m-%dT%H:%M:%SZ))" > "$OUT"
          echo >> "$OUT"
          echo "## File list" >> "$OUT"
          git ls-files | sort >> "$OUT"
          echo >> "$OUT"
          echo "## Sources" >> "$OUT"
          git ls-files \
            ':!**/*.png' ':!**/*.jpg' ':!**/*.jpeg' ':!**/*.webp' ':!**/*.gif' \
            ':!**/*.keystore' ':!**/*.jks' \
          | while read -r f; do
              echo -e "\n\n-----8<----- FILE: $f -----8<-----\n" >> "$OUT"
              sed -n '1,5000p' "$f" >> "$OUT" || true
            done
          echo "Wrote $OUT"

      - name: Upload FULL_CODE_DUMP
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: FULL_CODE_DUMP
          path: FULL_CODE_DUMP.txt
