name: OnePlanAndroid — CI

on:
  push:
    branches: [ "refactor/v1" ]
  pull_request:
    branches: [ "refactor/v1" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Assemble debug APK
        run: gradle --no-daemon --stacktrace assembleDebug

      - name: Create FULL_CODE_DUMP.txt
        run: |
          echo "# Repo file dump" > FULL_CODE_DUMP.txt
          echo "" >> FULL_CODE_DUMP.txt
          git ls-files -z | xargs -0 -I{} bash -c 'echo "----- {} -----"; if file "{}" | grep -qi text; then sed -n "1,400p" "{}"; else echo "(binary)"; fi' >> FULL_CODE_DUMP.txt

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: oneplan-debug-apks
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload FULL_CODE_DUMP
        uses: actions/upload-artifact@v4
        with:
          name: FULL_CODE_DUMP
          path: FULL_CODE_DUMP.txt
