name: OnePlanAndroid — CI
on:
  push:
    branches: [ main, refactor/megaalpha ]
  pull_request:
    branches: [ main, refactor/megaalpha ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Bump versionCode (commit back with [skip ci] to avoid loops)
      - name: Bump versionCode
        run: |
          vc=$(cat .oneplan_versioncode 2>/dev/null || echo 1)
          vc=$((vc+1))
          echo "$vc" > .oneplan_versioncode
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .oneplan_versioncode
          git commit -m "chore(ci): bump versionCode to $vc [skip ci]" || echo "No changes"
          git push || true

      - name: Assemble debug APK
        run: gradle --no-daemon --stacktrace :app:assembleDebug

      - name: Upload APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: oneplanmegaalpha-debug-apks
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error

      - name: Generate FULL_CODE_DUMP.txt (root)
        run: |
          OUT="FULL_CODE_DUMP.txt"
          echo "# OnePlanMegaAlpha — full source dump ($(date -u +%Y-%m-%dT%H:%M:%SZ))" > "$OUT"
          echo >> "$OUT"
          echo "## File list" >> "$OUT"
          git ls-files | sort >> "$OUT"
          echo >> "$OUT"
          echo "## Sources" >> "$OUT"
          git ls-files \
            ':!**/*.png' ':!**/*.jpg' ':!**/*.jpeg' ':!**/*.webp' ':!**/*.gif' \
            ':!**/*.keystore' ':!**/*.jks' \
            | while read -r f; do
              echo -e "\n\n-----8<----- FILE: $f -----8<-----\n" >> "$OUT"
              sed -n '1,5000p' "$f" >> "$OUT" || true
            done

      - name: Commit FULL_CODE_DUMP.txt to repo (skip CI)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add FULL_CODE_DUMP.txt
          git commit -m "chore(ci): refresh FULL_CODE_DUMP [skip ci]" || echo "No changes"
          git push || true

      - name: Upload FULL_CODE_DUMP artifact
        uses: actions/upload-artifact@v4
        with:
          name: FULL_CODE_DUMP
          path: FULL_CODE_DUMP.txt
