name: OnePlanAndroid — CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Make gradlew executable
        run: chmod +x ./gradlew || true
      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload Debug APKs
        uses: actions/upload-artifact@v4
        with:
          name: oneplan-debug-apks
          path: '**/build/outputs/apk/debug/*.apk'
