name: OnePlanAndroid — CI
on:
  push:
    branches: [ main, refactor/** ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Ensure gradle.properties exists (AndroidX)
        run: |
          touch gradle.properties
          grep -q "android.useAndroidX=true" gradle.properties || echo "android.useAndroidX=true" >> gradle.properties

      - name: Build debug APK
        run: ./gradlew --no-daemon --stacktrace assembleDebug

      - name: Upload Debug APKs
        uses: actions/upload-artifact@v4
        with:
          name: oneplan-debug-apks
          path: '**/build/outputs/apk/debug/*.apk'

      - name: Full code dump
        run: |
          echo "===== FULL REPO CODE DUMP $(date) =====" > FULL_CODE_DUMP.txt
          find . -type f -not -path "./.git/*" -print | sort >> FULL_CODE_DUMP.txt
          echo "" >> FULL_CODE_DUMP.txt
          for f in $(find . -type f -not -path "./.git/*" | sort); do
            echo "---------- \$f ----------" >> FULL_CODE_DUMP.txt
            (sed -n '1,400p' "\$f" || true) >> FULL_CODE_DUMP.txt
            echo "" >> FULL_CODE_DUMP.txt
          done
      - name: Upload code dump
        uses: actions/upload-artifact@v4
        with:
          name: repo-full-code-dump
          path: FULL_CODE_DUMP.txt
