name: OnePlanAndroid — CI
on:
  push:
    branches: [ "refactor/v1" ]
  pull_request:
    branches: [ "refactor/v1" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v3
      - name: Build debug APK
        run: gradle --no-daemon --stacktrace assembleDebug
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: oneplan-debug-apks
          path: app/build/outputs/apk/debug/*.apk
      - name: Generate FULL_CODE_DUMP.txt
        shell: bash
        run: |
          echo "OnePlan — full code dump ($(date -u +%FT%TZ))" > FULL_CODE_DUMP.txt
          git ls-files | sort | while read -r f; do
            echo -e "\n\n===== FILE: $f =====\n" >> FULL_CODE_DUMP.txt
            sed -e 's/\t/    /g' "$f" >> FULL_CODE_DUMP.txt || true
          done
      - name: Upload FULL_CODE_DUMP.txt
        uses: actions/upload-artifact@v4
        with:
          name: oneplan-code-dump
          path: FULL_CODE_DUMP.txt
