name: OnePlanAndroid — CI
on:
  push: { branches: [ main, megaalpha ] }
  pull_request: { branches: [ main, megaalpha ] }
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Bump versionCode
        run: |
          VC=$(awk '{print $1+1}' .oneplan_versioncode 2>/dev/null || echo 1)
          echo $VC > .oneplan_versioncode

      - name: Build debug APK
        run: gradle --no-daemon --stacktrace :app:assembleDebug

      - name: Upload APK(s)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: oneplanalpha-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: warn

      - name: Full code dump (repo file)
        if: always()
        run: |
          bash ./dump_code.sh || true

      - name: Upload FULL_CODE_DUMP
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: FULL_CODE_DUMP
          path: FULL_CODE_DUMP.txt

      - name: Commit dump (CI)
        if: github.event_name == 'push'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add FULL_CODE_DUMP.txt .oneplan_versioncode || true
          git commit -m "ci: update FULL_CODE_DUMP + versionCode [skip ci]" || echo "No changes"
          git push || echo "No push"
