name: OnePlanAndroid — CI

on:
  push:
    branches: [ "refactor/v1" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - uses: gradle/actions/setup-gradle@v3
      - name: Assemble Debug
        run: |
          ./gradlew --no-daemon --stacktrace assembleDebug
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: oneplan-debug-apks
          path: app/build/outputs/apk/debug/*.apk
      - name: Full Code Dump
        run: |
          mkdir -p dump && git ls-files > dump/FULL_CODE_DUMP.txt
      - name: Upload Dump
        uses: actions/upload-artifact@v4
        with:
          name: FULL_CODE_DUMP
          path: dump/**
