name: Unpack OnePlan ZIP
on:
  workflow_dispatch:

jobs:
  unpack:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Unzip OnePlan
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          unzip -o oneplan-android-combined.zip -d extracted
          shopt -s dotglob
          mv -f extracted/* .
          rm -rf extracted

      - name: Commit unpacked files
        run: |
          git config user.name "oneplan-bot"
          git config user.email "oneplan-bot@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "bootstrap: unpack OnePlan Android project + CI"
            git push
          fi
