name: Unpack OnePlan ZIP
on:
  workflow_dispatch:

jobs:
  unpack:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract OnePlan
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          unzip -o oneplan-android-combined.zip
          ls -la

      - name: Commit extracted files
        run: |
          git config user.name "oneplan-bot"
          git config user.email "oneplan-bot@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "unpacked OnePlan project"
            git push
          fi
