name: Unpack OnePlan ZIP
on:
  workflow_dispatch:

jobs:
  unpack:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract ZIP (already succeeded earlier; keeping it here)
        run: |
          python3 - <<'PY'
import zipfile, os, shutil
z = "oneplan-android-combined.zip"
assert os.path.exists(z), f"{z} not found"
tmp = "_tmp_unpack"
if os.path.isdir(tmp): shutil.rmtree(tmp)
os.makedirs(tmp, exist_ok=True)
with zipfile.ZipFile(z) as f: f.extractall(tmp)
# Move up (single top folder or many files)
entries = [os.path.join(tmp, e) for e in os.listdir(tmp)]
if len(entries) == 1 and os.path.isdir(entries[0]):
  src = entries[0]
  for n in os.listdir(src): shutil.move(os.path.join(src, n), ".")
else:
  for n in os.listdir(tmp): shutil.move(os.path.join(tmp, n), ".")
shutil.rmtree(tmp)
print("Extracted into repo root.")
PY

      - name: Show repo after extract
        run: |
          echo "Root listing:"
          ls -la
          echo "App listing:"
          ls -la app || true
          echo "Workflows listing:"
          ls -la .github/workflows || true

      - name: Commit & push (force-safe)
        run: |
          set -euxo pipefail
          git config user.name "oneplan-bot"
          git config user.email "oneplan-bot@users.noreply.github.com"

          # Ensure we're on main and up to date
          git checkout -B main
          git pull --rebase origin main || true

          # Stage and show what will be committed
          git add -A
          echo "Staged changes:"
          git status --porcelain || true

          # Commit even if there are many files; if nothing to commit, don't fail
          git commit -m "bootstrap: unpack OnePlan Android project + CI" || echo "No changes to commit"

          # Push (create main if needed). Use explicit ref to avoid HEAD confusion.
          git push origin HEAD:main
